import '@elevateart/ui/globals.css'
// import './globals.css'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </head>
      <body className='h-screen w-screen bg-background'>{children}</body>
      <footer className='absolute fixed bottom-0 text-accents_6 text-xs flex items-center justify-center w-full py-3'>
        inspired by manifold & zora
      </footer>
    </html>
  )
}
