name: repository-deployment/bundle-images-cancel
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://staging.elevate.art/api/assets/cancel-deployments' \
          --header 'Authorization: Bearer ${{ secrets.GH_API_SECRET_KEY }}'
